# Generated by Django 3.2.16 on 2022-11-08 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="ادمین"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="unvalid phonenumber", regex="^(\\+98|0)?9\\d{9}$"
                    )
                ],
                verbose_name="شماره تلفن",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("admin", "ادمین"),
                    ("business", "تجاری"),
                    ("client", "مشتری"),
                ],
                default="client",
                max_length=10,
                verbose_name="نوع کاربر",
            ),
        ),
    ]
