# Generated by Django 3.2.16 on 2022-12-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20221204_2103"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_point",
            field=models.PositiveIntegerField(default=1, verbose_name="امتیاز کاربر"),
            preserve_default=False,
        ),
    ]
