# Generated by Django 3.2.16 on 2022-12-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_user_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_point',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز کاربر'),
        ),
    ]
