# Generated by Django 3.2.16 on 2022-11-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0003_alter_category_options"),
        ("shop", "0002_auto_20221114_1357"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=125)),
                ("description", models.TextField()),
                ("feature", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("wait", "در حال بررسی"),
                        ],
                        max_length=12,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                (
                    "credit_sale",
                    models.BooleanField(default=False, verbose_name="فروش اعتباری"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.shop"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
