# Generated by Django 3.2.16 on 2022-12-01 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_auto_20221201_1401"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="discount_amount",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promotion",
            name="product",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount",
                to="product.product",
            ),
            preserve_default=False,
        ),
    ]
