# Generated by Django 3.2.16 on 2022-12-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_auto_20221201_1402"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerClub",
        ),
    ]
