# Generated by Django 3.2.16 on 2022-12-02 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_delete_customerclub"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "تخقیف", "verbose_name_plural": "تخفیفات"},
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount_amount",
            field=models.PositiveIntegerField(verbose_name="مقدار تخقیف"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount",
                to="product.product",
                verbose_name="مصحصول",
            ),
        ),
    ]
