# Generated by Django 3.2.16 on 2022-11-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="logo",
            field=models.ImageField(upload_to="logo/", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=125, verbose_name="عنوان"),
        ),
    ]
