# Generated by Django 3.2.16 on 2022-12-03 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="درصد کمیسیون",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
            options={
                "unique_together": {("percent", "category")},
            },
        ),
    ]
