# Generated by Django 3.2.16 on 2022-12-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_commission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commission",
            options={"verbose_name": "کمیسیون", "verbose_name_plural": "کمیسیون ها"},
        ),
        migrations.AlterField(
            model_name="commission",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
                verbose_name="دسته بندی",
            ),
        ),
    ]
