# Generated by Django 3.2.16 on 2022-12-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_auto_20221203_1756"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
    ]
