# Generated by Django 3.2.16 on 2022-11-02 07:28

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("description", ckeditor.fields.RichTextField(verbose_name="محتوا")),
                (
                    "thumbnail",
                    models.ImageField(upload_to="images/", verbose_name="تصویر زمینه"),
                ),
                ("publish_time", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={"status": "admin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقاله ها",
            },
        ),
    ]
