# Generated by Django 3.2.16 on 2022-11-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="publish_time",
            field=models.DateTimeField(verbose_name="زمان انتشار"),
        ),
    ]
