# Generated by Django 3.2.16 on 2022-11-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvertisingBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_row_first_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف اول عکس اول"
                    ),
                ),
                (
                    "first_row_second_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف اول عکس دوم"
                    ),
                ),
                (
                    "first_row_third_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف اول عگس سوم "
                    ),
                ),
                (
                    "first_row_fourth_image",
                    models.ImageField(
                        upload_to="images/suggestion/",
                        verbose_name="ردیف اول عکس چهارم",
                    ),
                ),
                (
                    "second_row_first_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف دوم عکس اول"
                    ),
                ),
                (
                    "second_row_second_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف دوم عکس دوم"
                    ),
                ),
                (
                    "second_row_third_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف دوم عکس سوم"
                    ),
                ),
                (
                    "second_row_fourth_image",
                    models.ImageField(
                        upload_to="images/suggestion/",
                        verbose_name="ردیف دوم عکس چهارم",
                    ),
                ),
                (
                    "third_row_first_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف سوم عکس اول"
                    ),
                ),
                (
                    "third_row_second_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف سوم عکس دوم "
                    ),
                ),
                (
                    "third_row_third_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف سوم عکس سوم"
                    ),
                ),
                (
                    "third_row_fourth_image",
                    models.ImageField(
                        upload_to="images/suggestion/",
                        verbose_name="ردیف سوم عکس چهارم",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoticeBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_banner", models.ImageField(upload_to="banner/")),
                ("header_banner_mobile", models.ImageField(upload_to="banner/")),
                ("header_banner_url", models.ImageField(upload_to="banner/")),
                ("row_one_first", models.ImageField(upload_to="banner/")),
                ("row_one_second", models.ImageField(upload_to="banner/")),
                ("row_second_first", models.ImageField(upload_to="banner/")),
                ("row_second_second", models.ImageField(upload_to="banner/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
