# Generated by Django 3.2.16 on 2022-11-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticebanner",
            name="header_banner_url",
            field=models.URLField(),
        ),
    ]
