# Generated by Django 3.2.16 on 2022-11-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0002_alter_noticebanner_header_banner_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticebanner",
            name="header_banner_url",
        ),
    ]
