# Generated by Django 3.2.16 on 2022-11-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0004_auto_20221102_1524"),
    ]

    operations = [
        migrations.RenameField(
            model_name="noticebanner",
            old_name="row_one_first",
            new_name="first_row_first",
        ),
        migrations.RenameField(
            model_name="noticebanner",
            old_name="row_one_first_url",
            new_name="first_row_first_url",
        ),
        migrations.RenameField(
            model_name="noticebanner",
            old_name="row_one_second",
            new_name="first_row_second",
        ),
        migrations.RenameField(
            model_name="noticebanner",
            old_name="row_one_second_url",
            new_name="first_row_second_url",
        ),
        migrations.RenameField(
            model_name="noticebanner",
            old_name="row_second_first",
            new_name="second_row_first",
        ),
        migrations.RenameField(
            model_name="noticebanner",
            old_name="row_second_first_url",
            new_name="second_row_first_url",
        ),
        migrations.RenameField(
            model_name="noticebanner",
            old_name="row_second_second",
            new_name="second_row_second",
        ),
        migrations.RenameField(
            model_name="noticebanner",
            old_name="row_second_second_url",
            new_name="second_row_second_url",
        ),
    ]
