# Generated by Django 3.2.16 on 2022-11-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0006_auto_20221105_1225"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisingbanner",
            options={
                "verbose_name": "بنر تبلیغاتی",
                "verbose_name_plural": "بنرهای تبلیغاتی",
            },
        ),
        migrations.AlterModelOptions(
            name="noticebanner",
            options={
                "verbose_name": "بنر اطالع رسانی",
                "verbose_name_plural": "بنرهای اطلاع رسانی",
            },
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="first_row_first_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="first_row_fourth_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="first_row_second_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="first_row_third_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="second_row_first_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="second_row_fourth_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="second_row_second_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="second_row_third_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="third_row_first_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="third_row_fourth_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="third_row_second_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="advertisingbanner",
            name="third_row_third_url",
            field=models.URLField(verbose_name="آدزس"),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="first_row_first",
            field=models.ImageField(
                upload_to="banner/", verbose_name="ردیف اول عکس اول"
            ),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="first_row_first_url",
            field=models.URLField(verbose_name="ردیف اول لینک اول"),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="first_row_second",
            field=models.ImageField(
                upload_to="banner/", verbose_name="ردیف اول عکس دوم"
            ),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="first_row_second_url",
            field=models.URLField(verbose_name="ردیف اول لینک دوم"),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="header_banner",
            field=models.ImageField(upload_to="banner/", verbose_name="بنر هدر"),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="header_banner_mobile",
            field=models.ImageField(
                upload_to="banner/", verbose_name="بنر هدر سایز موبایل"
            ),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="header_banner_url",
            field=models.URLField(verbose_name="لینک بنر هدر"),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="second_row_first",
            field=models.ImageField(
                upload_to="banner/", verbose_name="ردیف دوم عکس اول"
            ),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="second_row_first_url",
            field=models.URLField(verbose_name="ردیف دوم لینک اول"),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="second_row_second",
            field=models.ImageField(
                upload_to="banner/", verbose_name="ردیف دوم عکس دوم"
            ),
        ),
        migrations.AlterField(
            model_name="noticebanner",
            name="second_row_second_url",
            field=models.URLField(verbose_name="ردیف دوم لینک دوم"),
        ),
    ]
