# Generated by Django 3.2.16 on 2022-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0007_auto_20221108_1229"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "special_suggestion_text",
                    models.CharField(max_length=255, verbose_name="متن محصولات ویژه"),
                ),
                (
                    "special_suggestion_image",
                    models.ImageField(
                        upload_to="partial/", verbose_name=" عکس  محصولات ویژه"
                    ),
                ),
                (
                    "best_seller_text",
                    models.CharField(max_length=255, verbose_name="متن محولات پرفروش"),
                ),
                (
                    "best_seller_image",
                    models.ImageField(
                        upload_to="partial/", verbose_name="متن محولات پرفروش"
                    ),
                ),
                (
                    "product_text",
                    models.CharField(max_length=255, verbose_name="متن محصولات"),
                ),
                (
                    "product_image",
                    models.ImageField(
                        upload_to="partial/", verbose_name=" عکس  محصولات"
                    ),
                ),
                (
                    "mid_banner_text",
                    models.CharField(max_length=255, verbose_name="متن شگفتانه"),
                ),
                (
                    "mid_banner_image",
                    models.ImageField(upload_to="partial/", verbose_name="عکس شگفتانه"),
                ),
            ],
            options={
                "verbose_name": "ایتم صفحه  اول",
                "verbose_name_plural": "ایتم های صفحه اول",
            },
        ),
    ]
