# Generated by Django 3.2.16 on 2022-12-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertise", "0008_partialdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="عنوان"
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "minimum_card_amount",
                    models.IntegerField(default=0, verbose_name="حداقل سبد خرید"),
                ),
                ("discount_rate", models.IntegerField(default=0, verbose_name="تخفیف")),
                (
                    "expired_after_day",
                    models.IntegerField(default=0, verbose_name="انقضا پس از ... روز"),
                ),
                ("needed_point", models.IntegerField(verbose_name="امتیاز مورد نیاز")),
            ],
            options={
                "verbose_name": "کارت تخفیف",
                "verbose_name_plural": "کارت های تخفیف",
            },
        ),
        migrations.CreateModel(
            name="PointAfterBuy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_amount", models.IntegerField(default=0, verbose_name="از قیمت")),
                ("to_amount", models.IntegerField(default=0, verbose_name="تا قیمت")),
                ("prize_point", models.IntegerField(verbose_name="امتیاز جایزه")),
            ],
            options={
                "verbose_name": "امتیاز پس از خرید",
                "verbose_name_plural": "امتیاز پس از خرید",
            },
        ),
    ]
