# Generated by Django 3.2.16 on 2022-10-31 06:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "درباره ما",
                "verbose_name_plural": "دربازه ما",
            },
        ),
        migrations.CreateModel(
            name="CreditPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "شرایط خرید اعتباری",
                "verbose_name_plural": "شرایط خرید اعتباری",
            },
        ),
        migrations.CreateModel(
            name="OrderPlacing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "مراحل ثبت سفارش",
                "verbose_name_plural": "مراحل ثبت سفارش",
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "قوانین",
                "verbose_name_plural": "قوانین",
            },
        ),
        migrations.CreateModel(
            name="StoreRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "شرایط ثبت فروشگاه",
                "verbose_name_plural": "شرایط ثبت فروشگاه",
            },
        ),
    ]
