# Generated by Django 3.2.16 on 2022-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="اسلایدر")),
            ],
            options={
                "verbose_name": "اسلایدر",
                "verbose_name_plural": "اسلایدرها",
            },
        ),
    ]
