# Generated by Django 3.2.16 on 2022-10-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_slider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to="sliders/", verbose_name="اسلایدر"),
        ),
    ]
