# Generated by Django 3.2.16 on 2022-11-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_noticebanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_row_first_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف اول عکس اول"
                    ),
                ),
                (
                    "first_row_second_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف اول عکس دوم"
                    ),
                ),
                (
                    "first_row_third_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف اول عگس سوم "
                    ),
                ),
                (
                    "first_row_fourth_image",
                    models.ImageField(
                        upload_to="images/suggestion/",
                        verbose_name="ردیف اول عکس چهارم",
                    ),
                ),
                (
                    "second_row_first_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف دوم عکس اول"
                    ),
                ),
                (
                    "second_row_second_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف دوم عکس دوم"
                    ),
                ),
                (
                    "second_row_third_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف دوم عکس سوم"
                    ),
                ),
                (
                    "second_row_fourth_image",
                    models.ImageField(
                        upload_to="images/suggestion/",
                        verbose_name="ردیف دوم عکس چهارم",
                    ),
                ),
                (
                    "third_row_first_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف سوم عکس اول"
                    ),
                ),
                (
                    "third_row_second_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف سوم عکس دوم "
                    ),
                ),
                (
                    "third_row_third_image",
                    models.ImageField(
                        upload_to="images/suggestion/", verbose_name="ردیف سوم عکس سوم"
                    ),
                ),
                (
                    "third_row_fourth_image",
                    models.ImageField(
                        upload_to="images/suggestion/",
                        verbose_name="ردیف سوم عکس چهارم",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
