# Generated by Django 3.2.16 on 2022-11-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_advertisingbanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="creditpurchase",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderplacing",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rule",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storeregistration",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
    ]
