# Generated by Django 3.2.16 on 2022-11-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0006_auto_20221101_1102"),
    ]

    operations = [
        migrations.CreateModel(
            name="r",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
