# Generated by Django 3.2.16 on 2022-12-04 14:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0008_auto_20221102_1457"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="شماره تلفن")),
                (
                    "phone2",
                    models.CharField(max_length=11, verbose_name="شماره تلفن 2"),
                ),
                (
                    "phone3",
                    models.CharField(max_length=11, verbose_name="شماره تلفن 3"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("explanation", ckeditor.fields.RichTextField(verbose_name="توضیحات")),
                (
                    "address",
                    ckeditor.fields.RichTextField(
                        default="", max_length=1000, verbose_name="آدرس"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "تماس با ما",
            },
        ),
    ]
