# Generated by Django 3.2.16 on 2022-12-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0009_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "تماس با ما", "verbose_name_plural": "تماس با ما"},
        ),
    ]
