# Generated by Django 3.2.16 on 2022-11-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={"verbose_name": "فروشگاه", "verbose_name_plural": "فروشگاه ها"},
        ),
        migrations.AlterField(
            model_name="shop",
            name="logo",
            field=models.ImageField(upload_to="shop/logo"),
        ),
    ]
