# Generated by Django 3.2.16 on 2022-11-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_auto_20221115_1209"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="image_license",
            new_name="license_image",
        ),
        migrations.RenameField(
            model_name="shop",
            old_name="image_national_card",
            new_name="national_card_image",
        ),
    ]
