# Generated by Django 3.2.16 on 2022-11-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_auto_20221115_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="first_name",
            field=models.CharField(default=1, max_length=125, verbose_name="نام "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shop",
            name="last_name",
            field=models.CharField(
                default=1, max_length=125, verbose_name="نام خانوادگی"
            ),
            preserve_default=False,
        ),
    ]
