# Generated by Django 3.2.16 on 2022-11-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_auto_20221115_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="sheba_no",
            field=models.CharField(default=1, max_length=16, verbose_name="شماره شبا"),
            preserve_default=False,
        ),
    ]
