# Generated by Django 3.2.16 on 2022-12-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_shop_sheba_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="last_name",
        ),
    ]
