# Generated by Django 3.2.16 on 2022-12-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0016_alter_comment_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="ایمیل یا نام"
            ),
        ),
    ]
