# Generated by Django 3.2.16 on 2022-10-31 09:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("title", models.CharField(max_length=125)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "خوانده نشده"),
                            ("closed", "بسته شده"),
                            ("pending", "در حال بررسی"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("unread", "خوانده نشده"),
                            ("closed", "بسته شده"),
                            ("pending", "در حال بررسی"),
                        ],
                        max_length=15,
                    ),
                ),
                ("ticket_number", models.CharField(default=uuid.uuid4, max_length=6)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت ها",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("message", models.TextField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ticket.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام",
                "verbose_name_plural": "پیام ها",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files/")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ticket.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل ",
                "verbose_name_plural": "فایل ها",
            },
        ),
    ]
