# Generated by Django 3.2.16 on 2022-10-31 09:32

from django.db import migrations, models

import utilities.utils


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(
                default=utilities.utils.create_random_number, max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
