# Generated by Django 3.2.16 on 2022-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_auto_20221031_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[("high", "زیاد"), ("medium", "متوسط"), ("low", "کم")],
                max_length=15,
            ),
        ),
    ]
