# Generated by Django 3.2.16 on 2022-11-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0004_auto_20221108_1253"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[("admin", "ادمین"), ("customer", "مشتری")],
                default=1,
                max_length=12,
            ),
            preserve_default=False,
        ),
    ]
