# Generated by Django 3.2.16 on 2022-12-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0006_alter_message_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[("admin", "ادمین"), ("customer", "مشتری")],
                default="customer",
                max_length=12,
                verbose_name="ارسال کننده",
            ),
        ),
    ]
