# Generated by Django 3.2.16 on 2022-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0007_alter_message_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("unread", "خوانده نشده"),
                    ("closed", "بسته شده"),
                    ("pending", "در حال بررسی"),
                ],
                default="unread",
                max_length=15,
                verbose_name="وضعیت",
            ),
        ),
    ]
