# Generated by Django 3.2.16 on 2022-11-02 07:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="phone_number",
            field=models.CharField(default=9108462478, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apply",
            name="job",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="job.jon"
            ),
        ),
        migrations.AlterField(
            model_name="apply",
            name="resume",
            field=models.FileField(
                upload_to="file/",
                validators=[
                    django.core.validators.RegexValidator(
                        message="unvalid phonenumber", regex="^(\\+98|0)?9\\d{9}$"
                    )
                ],
            ),
        ),
    ]
