# Generated by Django 3.2.16 on 2022-11-08 09:23

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_auto_20221102_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="description",
            field=models.TextField(max_length=500, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="apply",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="apply",
            name="first_name",
            field=models.CharField(max_length=125, verbose_name=" نام"),
        ),
        migrations.AlterField(
            model_name="apply",
            name="job",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.job",
                verbose_name="آگهی شغلی",
            ),
        ),
        migrations.AlterField(
            model_name="apply",
            name="last_name",
            field=models.CharField(max_length=125, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="apply",
            name="phone_number",
            field=models.CharField(max_length=11, verbose_name="شماره تماس"),
        ),
        migrations.AlterField(
            model_name="apply",
            name="resume",
            field=models.FileField(upload_to="file/", verbose_name="رزومه"),
        ),
        migrations.AlterField(
            model_name="job",
            name="active",
            field=models.BooleanField(default=True, verbose_name="فعال؟"),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="job",
            name="thumbnail",
            field=models.ImageField(upload_to="images", verbose_name="تصویر"),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عتوان شغلی"),
        ),
    ]
