# Generated by Django 3.2.16 on 2022-11-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_alter_apply_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="job.job",
                verbose_name="آگهی شغلی",
            ),
        ),
    ]
