# Generated by Django 3.2.16 on 2022-12-02 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "در حال بررسی"),
                            ("A", "تایید شده"),
                            ("R", "رد شده"),
                        ],
                        default="P",
                        max_length=255,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "cheque_image",
                    models.ImageField(upload_to="check/images/", verbose_name="عکس چک"),
                ),
                (
                    "national_image",
                    models.ImageField(
                        upload_to="check/images/", verbose_name="عکس کارت ملیگ"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="مبلغ چک")),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "چک",
                "verbose_name_plural": "چک ها",
            },
        ),
    ]
