# Generated by Django 3.2.16 on 2022-12-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "coupon_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "minimum_card_amount",
                    models.IntegerField(verbose_name="حداقل سبد خرید"),
                ),
                ("discount_rate", models.IntegerField(verbose_name="تخفیف")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="فعال")),
                ("expired_date", models.DateTimeField(verbose_name="معتبر تا")),
            ],
            options={
                "verbose_name": "کوپن",
                "verbose_name_plural": "کوپن ها",
            },
        ),
    ]
