# Generated by Django 3.2.16 on 2022-12-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_auto_20221204_1835"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="active",
        ),
    ]
