# Generated by Django 3.2.16 on 2022-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_remove_coupon_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expired_date",
            field=models.DateField(verbose_name="معتبر تا"),
        ),
    ]
