# Generated by Django 3.2.16 on 2022-12-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_auto_20221204_2128"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={},
        ),
    ]
