# Generated by Django 3.2.16 on 2022-12-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_auto_20221207_0039"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "کوپن", "verbose_name_plural": "کوپن ها"},
        ),
    ]
