# Generated by Django 3.2.16 on 2022-12-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0016_order_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheque",
            name="used",
            field=models.BooleanField(default=False, verbose_name="استفاده شده>"),
        ),
    ]
