# Generated by Django 3.2.16 on 2022-12-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0017_cheque_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_tracking_code",
            field=models.CharField(
                default=1, max_length=125, verbose_name="کد پیگری پرداخت"
            ),
            preserve_default=False,
        ),
    ]
